[build.environment]
  YARN_VERSION = "1.12.5"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"
  NODE_VERSION = "14.15.0"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
